//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerParcial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdViviendasItmEntities : DbContext
    {
        public bdViviendasItmEntities()
            : base("name=bdViviendasItmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAgencia> tblAgencias { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblTipoVivienda> tblTipoViviendas { get; set; }
        public virtual DbSet<tblVenta> tblVentas { get; set; }
        public virtual DbSet<tblVivienda> tblViviendas { get; set; }
    }
}
