//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerParcial.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblVenta
    {
        public int Id { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal Valor { get; set; }
        public string MetodoPago { get; set; }
        public string NitAgencia { get; set; }
        public string DocumentoCliente { get; set; }
        public string IdVivienda { get; set; }

        [JsonIgnore]
        public virtual tblAgencia tblAgencia { get; set; }
        [JsonIgnore]
        public virtual tblCliente tblCliente { get; set; }
        [JsonIgnore]
        public virtual tblVivienda tblVivienda { get; set; }
    }
}
