//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerParcial.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblVivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVivienda()
        {
            this.tblVentas = new HashSet<tblVenta>();
        }
    
        public string Id { get; set; }
        public int NumCuartos { get; set; }
        public int NumBaños { get; set; }
        public decimal Tamaño { get; set; }
        public int NumPisos { get; set; }
        public string Accesorios { get; set; }
        public bool Activo { get; set; }
        public int IdTipoVivienda { get; set; }
    
        public virtual tblTipoVivienda tblTipoVivienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblVenta> tblVentas { get; set; }
    }
}
